### ISSUE TITLE
Upgrade to newer version

### ISSUE THREAD

**Issue by sultaniman** [conda-forge/requirements-parser-feedstock#5]
### Comment:

Hey team,

Can you please upgrade recipe to least version 0.5.0 because I've been working to introduce a new package which depends on versions `>=0.5.0` https://github.com/conda-forge/staged-recipes/pull/25653

Thanks.

**Comment by wolfv** [comment]
Done!

**Comment by sultaniman** [comment]
Thank you Wolf!
